<?php

namespace Altgeek\ForumBundle\Repository;

/**
 * UberTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UberTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
