altgeek_core:
    resource: "@AltgeekCoreBundle/Resources/config/routing.yml"
    prefix:   /

altgeek_forum:
    resource: "@AltgeekForumBundle/Resources/config/routing.yml"
    prefix:   /forum

altgeek_user:
    resource: "@AltgeekUserBundle/Resources/config/routing.yml"
    prefix:   /user

login:
    path: /login
    defaults:
        _controller: AltgeekUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout